Traceback (most recent call last):
  File "/var/tmp/pbs.8992170.pbs/plotfixed.py", line 74, in <module>
    anim.save('anim.mp4', writer=writervideo)
  File "/rds/general/user/mf620/home/anaconda3/lib/python3.11/site-packages/matplotlib/animation.py", line 1105, in save
    anim._draw_next_frame(d, blit=False)
  File "/rds/general/user/mf620/home/anaconda3/lib/python3.11/site-packages/matplotlib/animation.py", line 1140, in _draw_next_frame
    self._draw_frame(framedata)
  File "/rds/general/user/mf620/home/anaconda3/lib/python3.11/site-packages/matplotlib/animation.py", line 1768, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/pbs.8992170.pbs/plotfixed.py", line 62, in update_plot
    plt.scatter(400*partx[ii+1,:],400*party[ii+1,:],c='black',s=0.1)
                    ~~~~~^^^^^^^^
IndexError: index 6 is out of bounds for axis 0 with size 6
